spring.application.name=Master_Project
spring.application.name=CampusOperations
 
server.port=9001
 
spring.datasource.username=meghana
spring.datasource.password=nQ8!Fw$+#IhqRFME
 
 
spring.datasource.url=jdbc:postgresql://192.168.20.20:5432/scores
 
#spring.datasource.url=jdbc:postgresql://192.168.20.21:5432/scores_qa?ApplicationName=Your_Name
#spring.datasource.username=dev_read_user
#spring.datasource.password=XY#q%9NdcVFU4Rpb
 
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver
 
# ===============================
# Hibernate JPA Configuration
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
 
# HikariCP Configuration to fix connection validation warnings
spring.datasource.hikari.max-lifetime=600000
#spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
 
 
 
spring.datasource.hikari.maximum-pool-size=10
 
spring.datasource.hikari.minimum-idle=0
 
spring.datasource.hikari.idle-timeout=50000
 
spring.datasource.hikari.connection-timeout=300000
 